apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  labels:
    app: java-app
spec:
  selector:
    matchLabels:
        app: java-app
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: 720766170633.dkr.ecr.us-east-2.amazonaws.com/java-app:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always